name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller MosaicGenerator.spec
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
